language: python
before_install:
- pip install poetry
install:
- poetry install -v
- pip install pytest
script:
  - pytest
#before_deploy:
#  - poetry build
#deploy:
#  provider: script
#  script: poetry publish
