language: python
python:
  - 3.6
before_install:
- pip install poetry
install:
- poetry install -v
- pip install pytest
- pip install pytest-cov
- pip install coveralls
script:
  - pytest --cov=gene_outlier_detection/
  - black --check gene_outlier_detection/
  - black --check tests/
after_success:
  - coveralls
#before_deploy:
#  - poetry build
#deploy:
#  provider: script
#  script: poetry publish
